# Generated by Django 3.0.8 on 2020-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0003_purchase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
